sever:
  port:80
spring:
  application:
    name: book-my-ticket
  datasource:
    url: jdbc:mysql://localhost:3306/book-my-ticket?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formate_sql: ture
  data:
    redis:
      url: redis://localhost:6379
admin:
  email: admin@gmail.com
  password: admin1234
